name: Run Node.js script and push files

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # every Saturday at 13:00 (1:00 PM) UTC
  push:
    branches:
      - 'main'  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run script
        env:
          API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          node index.js
      - name: Pull latest changes
        run: git pull origin main
      - name: Push files to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated push from GitHub Actions workflow"
          git push -u origin main
